module.exports.attractions = [
    'Mount Fuji',
    'Imperial Tokyo',
    'Hiroshima Peace Memorial Park',
    'The Island Shrine of Itsukushima, Miyajima',
    'Osaka Castle',
    'Chūbu-Sangaku National Park',
    'The Atsuta Shrine',
    'Fukuoka Castle Ruins',
    'Fushimi Inari-taisha Shrine',
    'Koyasan Okunoin',
    'Kiyomizu-Dera',
    'Shinjuku Gyoen National Garden',
    'Hakone Open-Air Museum',
    'Naritasan Shinsho-ji',
    'Okinawa Churaumi Aquarium',
    'Matsumoto Castle',
    'Arashiyama Monkey Park',
    'Kenrokuen Garden'
]